apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
spec:
  replicas: 1   # 🔥 IMPORTANT CHANGE
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms
        image: vinaykn269/bms:latest
        ports:
        - containerPort: 3000
